### ISSUE TITLE
[Feature]]Add multiple Time Zone

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Digital-Clock#2]

**Comment by rishigupta1109** [comment]
can you provide some description like there 32 time zones so does you need all and does u need a dropdown to select or a list of clocks?

**Comment by Nitesh-thapliyal** [comment]
> can you provide some description like there 32 time zones so does you need all and does u need a dropdown to select or a list of clocks?

can you give users the option to select whatever time zone they want?

**Comment by rishigupta1109** [comment]
Yes i can provide a dropdown to select the time zone.
Can u tell me how many time zones to include?

**Comment by Nitesh-thapliyal** [comment]
> Yes i can provide a dropdown to select the time zone. Can u tell me how many time zones to include?

I think users should have the facility to select any time zone, so adding all time zone will be good.

**Comment by rishigupta1109** [comment]
Okay

**Comment by Nitesh-thapliyal** [comment]
> Okay

Can you share the snapshot of changes made, it will be helpful
