### ISSUE TITLE
[Feature] Add Background 

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Digital-Clock#3]

**Comment by nikhilpawar9** [comment]
I can add background. 
can you assign me this?

**Comment by nikhilpawar9** [comment]
I can add particle js as background

**Comment by Ashwani132003** [comment]
Please have a look on this background and tell me if I can add it or not. 
![Screenshot (187)](https://user-images.githubusercontent.com/76273539/135476884-0629389b-2543-4984-9871-fda658c8e2e3.png)

**Comment by Nitesh-thapliyal** [comment]
> I can add particle js as background

Go Ahead @nikhilpawar9  Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/
