### ISSUE TITLE
[Fix] Center align the timer

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Digital-Clock#5]

**Comment by K-ash-ish** [comment]
Hey, Can I work on this issue?

**Comment by Nitesh-thapliyal** [comment]
> Hey, Can I work on this issue?

Can you please join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by K-ash-ish** [comment]
I joined the DC server. I have to update my name on members.md file right

**Comment by devshub21** [comment]
Hey, I would like to work on this if the PR is not created ...
