### ISSUE TITLE
[Feature] Add multiple clock themes

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Digital-Clock#6]
- Give user access to select multiple clock themes, user can select the theme as per his/her interest.

**Comment by yasinbordbar** [comment]
Hi, please assign me to do this.

**Comment by Nitesh-thapliyal** [comment]
> Hi, please assign me to do this.

Can you please join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 join.bauddhikgeeks.tech

**Comment by yasinbordbar** [comment]
Done.
